# permissions for end users to edit realms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: realm-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kim
    app.kubernetes.io/part-of: kim
    app.kubernetes.io/managed-by: kustomize
  name: realm-editor-role
rules:
- apiGroups:
  - kim.io
  resources:
  - realms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kim.io
  resources:
  - realms/status
  verbs:
  - get
