---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: manager-role
  namespace: system
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - kim.io
  resources:
  - personalaccesstokens
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kim.io
  resources:
  - personalaccesstokens/finalizers
  verbs:
  - update
- apiGroups:
  - kim.io
  resources:
  - personalaccesstokens/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kim.io
  resources:
  - users
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kim.io
  resources:
  - users/finalizers
  verbs:
  - update
- apiGroups:
  - kim.io
  resources:
  - users/status
  verbs:
  - get
  - patch
  - update
