classDiagram
  direction LR

  class User
  class UserState
  class PersonalAccessToken

  class ServiceAccount

  User : ID string
  User : Username string
  User : Email string
  User : Expiration Time
  User : DisplayName string
  User : GivenName string
  User : FamilyName string
  User : Company string
  User : SecondaryMail string

  <<enumeration>> UserState
  UserState : WaitingForApproval
  UserState : Active
  UserState : Suspended
  UserState : Banned
  UserState "1" <--o User

  note for User "On User Activation, a ServiceAccount is provided to the user."
  ServiceAccount "1" <--o PersonalAccessToken
  User "1" o--> "0..1" ServiceAccount

  PersonalAccessToken : Deadline Time
  User o--> "0..*" PersonalAccessToken
